### ISSUE TITLE
Error deploy in docker

### ISSUE THREAD

**Issue by logajk** [redis-stack/redis-stack#404]
Hi!

When deploy my container I have this log traces:

```
OoO0Oo Redis is starting oO0OoO0OoO0Oo
8:C 19 May 2023 18:30:02.005 # Redis version=6.2.12, bits=64, commit=00000000, modified=0, pid=8, just started
8:C 19 May 2023 18:30:02.005 # Configuration loaded
8:M 19 May 2023 18:30:02.009 # You requested maxclients of 10000 requiring at least 10032 max file descriptors.
8:M 19 May 2023 18:30:02.009 # Server can't set maximum open files to 10032 because of OS error: Operation not permitted.
8:M 19 May 2023 18:30:02.010 # Current maximum open files is 4096. maxclients has been reduced to 4064 to compensate for low ulimit. If you need higher maxclients increase 'ulimit -n'.
8:M 19 May 2023 18:30:02.010 * monotonic clock: POSIX clock_gettime
8:M 19 May 2023 18:30:02.011 * Running mode=standalone, port=6379.
8:M 19 May 2023 18:30:02.011 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
8:M 19 May 2023 18:30:02.011 # Server initialized
8:M 19 May 2023 18:30:02.011 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
8:M 19 May 2023 18:30:02.143 * <search> Redis version found by RedisSearch : 6.2.12 - oss
8:M 19 May 2023 18:30:02.143 * <search> RediSearch version 2.6.9 (Git=HEAD-b205a1d5)
8:M 19 May 2023 18:30:02.143 * <search> Low level api version 1 initialized successfully
8:M 19 May 2023 18:30:02.143 * <search> concurrent writes: OFF, gc: ON, prefix min length: 2, prefix max expansions: 200, query timeout (ms): 500, timeout policy: return, cursor read size: 1000, cursor max idle (ms): 300000, max doctable size: 1000000, max number of search results:  10000, search pool size: 20, index pool size: 8, 
8:M 19 May 2023 18:30:02.144 * <search> Initialized thread pool!
8:M 19 May 2023 18:30:02.144 * <search> Enabled diskless replication
8:M 19 May 2023 18:30:02.144 * <search> Enabled role change notification
8:M 19 May 2023 18:30:02.144 * Module 'search' loaded from /opt/redis-stack/lib/redisearch.so
8:M 19 May 2023 18:30:02.381 * <graph> Enabled role change notification
8:M 19 May 2023 18:30:02.381 * <graph> Starting up RedisGraph version 2.10.10.
8:M 19 May 2023 18:30:02.382 * <graph> Thread pool created, using 4 threads.
8:M 19 May 2023 18:30:02.382 * <graph> Maximum number of OpenMP threads set to 4
8:M 19 May 2023 18:30:02.382 * Module 'graph' loaded from /opt/redis-stack/lib/redisgraph.so
8:M 19 May 2023 18:30:02.411 * <timeseries> RedisTimeSeries version 10810, git_sha=78d8254a4ed499e4e24566ab76c9275130c8786b
8:M 19 May 2023 18:30:02.411 * <timeseries> Redis version found by RedisTimeSeries : 6.2.12 - oss
8:M 19 May 2023 18:30:02.411 * <timeseries> loaded default CHUNK_SIZE_BYTES policy: 4096
8:M 19 May 2023 18:30:02.411 * <timeseries> loaded server DUPLICATE_POLICY: block
8:M 19 May 2023 18:30:02.411 * <timeseries> Setting default series ENCODING to: compressed
8:M 19 May 2023 18:30:02.411 * <timeseries> Detected redis oss
8:M 19 May 2023 18:30:02.412 * <timeseries> Enabled diskless replication
8:M 19 May 2023 18:30:02.412 * Module 'timeseries' loaded from /opt/redis-stack/lib/redistimeseries.so
8:M 19 May 2023 18:30:02.439 * <ReJSON> version: 20407 git sha: a4412b3 branch: HEAD
8:M 19 May 2023 18:30:02.440 * <ReJSON> Exported RedisJSON_V1 API
8:M 19 May 2023 18:30:02.440 * <ReJSON> Exported RedisJSON_V2 API
8:M 19 May 2023 18:30:02.440 * <ReJSON> Exported RedisJSON_V3 API
8:M 19 May 2023 18:30:02.440 * <ReJSON> Enabled diskless replication
8:M 19 May 2023 18:30:02.440 * <ReJSON> Created new data type 'ReJSON-RL'
8:M 19 May 2023 18:30:02.440 * Module 'ReJSON' loaded from /opt/redis-stack/lib/rejson.so
8:M 19 May 2023 18:30:02.440 * <search> Acquired RedisJSON_V3 API
8:M 19 May 2023 18:30:02.440 * <graph> Acquired RedisJSON_V1 API
8:M 19 May 2023 18:30:02.462 * <bf> RedisBloom version 2.4.5 (Git=unknown)
8:M 19 May 2023 18:30:02.463 * Module 'bf' loaded from /opt/redis-stack/lib/redisbloom.so
8:M 19 May 2023 18:30:02.482 * Ready to accept connections
node:internal/fs/utils:345
    throw err;
    ^
Error: ENOENT: no such file or directory, open '/opt/redis-stack/share/redisinsight/api/node_modules/dotenv/config'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1122:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module._preloadModules (node:internal/modules/cjs/loader:1282:12)
    at loadPreloadModules (node:internal/bootstrap/pre_execution:539:5)
    at prepareMainThreadExecution (node:internal/bootstrap/pre_execution:85:3)
    at node:internal/main/run_main_module:7:1 {

  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/opt/redis-stack/share/redisinsight/api/node_modules/dotenv/config'
```
I deployed my container in a NAS ASUSTOR AS3304T.

Anybody can help me with this error.

**Comment by chayim** [comment]
@logajk are you sure you have the ports exposed? By default port 6379 is exposed, but you may have to do something on your end.

**Comment by logajk** [comment]
I am sure the ports are exposed, in fact the response I get is always rejected.

**Comment by chayim** [comment]
@logajk redis-stack exposes ports, and assuming the docker is run with a port map (6379:6379 and 8001:8001 for insight)) you'll have the ports accessible, based on a standard configuration. 

@ViktarStarastsenka This looks like a redisinsight issue. Please take a look.

**Comment by GnaneshKunal** [comment]
@logajk Can you check with the latest redis-stack docker image?

**Comment by logajk** [comment]
@GnaneshKunal Hi, I tried with the latest version but I got the same error.

**Comment by ViktarStarastsenka** [comment]
@logajk , can you please provide the following information:

1. entry point script data - `cat /entrypoint.sh`
2. list of dotenv module files - `ls -la /opt/redis-stack/share/redisinsight/api/node_modules/dotenv`
3. list of files in the RedisInsight root folder - `ls -la /opt/redis-stack/share/redisinsight`
4. the full command you ran the docker container with - was it `docker run -d -p 8001:8001 redis/redis-stack`?

**Comment by logajk** [comment]
@ViktarStarastsenka here you are:

- **entry point data**

#!/usr/bin/dumb-init /bin/sh

### docker entrypoint script, for starting redis stack
BASEDIR=/opt/redis-stack
cd ${BASEDIR}

CMD=${BASEDIR}/bin/redis-server
if [ -f /redis-stack.conf ]; then
    CONFFILE=/redis-stack.conf
fi

if [ -z "${REDIS_DATA_DIR}" ]; then
    REDIS_DATA_DIR=/data
fi

# when running in redis-stack (as opposed to redis-stack-server)
if [ -f ${BASEDIR}/nodejs/bin/node ]; then
    ${BASEDIR}/nodejs/bin/node -r ${BASEDIR}/share/redisinsight/api/node_modules/dotenv/config share/redisinsight/api/dist/src/main.js dotenv_config_path=${BASEDIR}/share/redisinsight/.env &
fi

if [ -z "${REDISEARCH_ARGS}" ]; then
REDISEARCH_ARGS="MAXSEARCHRESULTS 10000 MAXAGGREGATERESULTS 10000"
fi

if [ -z "${REDISGRAPH_ARGS}" ]; then
REDISGRAPH_ARGS="MAX_QUEUED_QUERIES 25 TIMEOUT 1000 RESULTSET_SIZE 10000"
fi

${CMD} \
${CONFFILE} \
--dir ${REDIS_DATA_DIR} \
--protected-mode no \
--daemonize no \
--loadmodule /opt/redis-stack/lib/redisearch.so ${REDISEARCH_ARGS} \
--loadmodule /opt/redis-stack/lib/redisgraph.so ${REDISGRAPH_ARGS} \
--loadmodule /opt/redis-stack/lib/redistimeseries.so ${REDISTIMESERIES_ARGS} \
--loadmodule /opt/redis-stack/lib/rejson.so ${REDISJSON_ARGS} \
--loadmodule /opt/redis-stack/lib/redisbloom.so ${REDISBLOOM_ARGS} \
${REDIS_ARGS}

- **list of dotenv module files**

total 32
drwxrwxr-x   3 nobody 123  4096 Apr 24 14:05 .
drwxrwxr-x 333 nobody 123 12288 Apr 24 14:05 ..
-rw-r--r--   1 nobody 123  1294 Mar 30 11:47 LICENSE
-rw-r--r--   1 nobody 123   176 Mar 30 11:47 config.js
drwxrwxr-x   2 nobody 123  4096 Apr 24 14:05 lib
-rw-r--r--   1 nobody 123  1301 Mar 30 11:47 package.json

- **list of files in the RedisInsight root folder**

total 52
drwxr-xr-x 1 nobody  123  4096 Apr 24 14:05 .
drwxr-xr-x 1 nobody  123  4096 Apr 24 14:04 ..
-r-xr-xr-x 1 root   root   220 Apr 24 14:02 .env
-rw-rw-r-- 1 nobody  123 30574 Mar 30 12:04 LICENSE
drwxr-xr-x 4 nobody  123  4096 Apr 24 14:04 api
drwxr-xr-x 3 nobody  123  4096 Apr 24 14:04 ui

- **the full command you ran the docker container with - was it:**

I´m using docker-compose file:

version: '3.3'
services:
    redis-stack:
        container_name: redis-stack
        ports:
            - '6379:6379'
            - '8010:8001'
        image: 'redis/redis-stack:latest'

Regards.

**Comment by ViktarStarastsenka** [comment]
@logajk , thank you

can you also run this command in the running container? 

`cd /opt/redis-stack && /opt/redis-stack/nodejs/bin/node -r /opt/redis-stack/share/redisinsight/api/node_modules/dotenv/config.js share/redisinsight/api/dist/src/main.js dotenv_config_path=/opt/redis-stack/share/redisinsight/.env`

**Comment by logajk** [comment]
@ViktarStarastsenka the result of command is:

`bash: cd: /opt/redis-stack: No such file or directory`

**Comment by logajk** [comment]
@ViktarStarastsenka The result of command is:

`node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './lib/main'
Require stack:
- /opt/redis-stack/share/redisinsight/api/node_modules/dotenv/config.js
- internal/preload
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /opt/redis-stack/share/redisinsight/api/node_modules/dotenv/config.js:2:3
    at Object.<anonymous> (/opt/redis-stack/share/redisinsight/api/node_modules/dotenv/config.js:9:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/redis-stack/share/redisinsight/api/node_modules/dotenv/config.js',
    'internal/preload'
  ]
}`

**Comment by ViktarStarastsenka** [comment]
@logajk, thanks, this is interesting
can you also please send:
1. your node version - `/opt/redis-stack/nodejs/bin/node -v`
1. OS and its version
1. processor architecture - is it ARMv8 64-bit?

**Comment by logajk** [comment]
@ViktarStarastsenka Here you are:

1. Node version: **v16.15.1**
2. OS: **ADM (Asustor Data Master) 4.2.2.RI61**
3. Processor architecture is: **(aarch64) ARMv8 64-Bits.**

Regards.

**Comment by ViktarStarastsenka** [comment]
@logajk , thanks, we still cannot reproduce this case
the only guess is that the node cannot resolve modules without the file extension, maybe there is anything specific with the node or deployment?

also, the results of this command run in the container may shed some light:

`cd /opt/redis-stack && /opt/redis-stack/nodejs/bin/node --experimental-specifier-resolution=node -r /opt/redis-stack/share/redisinsight/api/node_modules/dotenv/config share/redisinsight/api/dist/src/main.js dotenv_config_path=/opt/redis-stack/share/redisinsight/.env`

**Comment by logajk** [comment]
@ViktarStarastsenka The result of the command is:

`node:internal/fs/utils:345
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/opt/redis-stack/share/redisinsight/api/node_modules/dotenv/config'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1122:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module._preloadModules (node:internal/modules/cjs/loader:1282:12)
    at loadPreloadModules (node:internal/bootstrap/pre_execution:539:5)
    at prepareMainThreadExecution (node:internal/bootstrap/pre_execution:85:3)
    at node:internal/main/run_main_module:7:1 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/opt/redis-stack/share/redisinsight/api/node_modules/dotenv/config'`

**Comment by chayim** [comment]
@logajk is this still an issue?
